PVSWeb/src/com/sh/pvs/model/dao/contabilidad/AccesoriosxCompraVentaDAO.java
package com.sh.pvs.model.dao.contabilidad;


public class AccesoriosxCompraVentaDAO {

	/*------------------ATRIBUTOS------------------*/
	public static final String ID = "id"; 
	public static final String IDCOMPRAVENTA = "compraVentaAccesorios.id";
	public static final String IDACCESORIO = "accesorio.id";
	public static final String PRECIO = "precio"; 
	public static final String CANTIDAD = "cantidad"; 
	
}

PVSWeb/src/com/sh/pvs/model/dao/contabilidad/CompraVentaAccesoriosDAO.java
package com.sh.pvs.model.dao.contabilidad;


public class CompraVentaAccesoriosDAO {

	/*------------------ATRIBUTOS------------------*/
	public static final String ID = "id"; 
	public static final String FECHA = "fecha"; 
	public static final String ESCOMPRA = "esCompra"; 
	public static final String ESPAGADO = "esPagado"; 
	public static final String NROFACTURA = "nroFactura"; 
	public static final String PROVEEDOR = "proveedor"; 
	public static final String OBSERVACIONES = "observaciones"; 
	public static final String VALOR = "valor";
	public static final String PLAZO = "plazo"; 
	
	public static final String IDCUENTA = "cuenta.id";
	public static final String IDUSUARIO = "usuario.id";
	public static final String IDCIA = "compania.id";
	
}

PVSWeb/src/com/sh/pvs/model/dao/contabilidad/InventarioAccesoriosDAO.java
package com.sh.pvs.model.dao.contabilidad;

public class InventarioAccesoriosDAO {
	
	/*------------------ATRIBUTOS------------------*/
	public static final String NOMBRE = "nombre";
	public static final String DESCRIPCION = "descripcion";
	public static final String ES_ACTIVO = "esActivo";
	public static final String IDCOMPANIA = "compania.id";
	public static final String CANTIDADDISPONIBLE = "cantidadDisponible";
	public static final String IDACCESORIO = "accesorio.id";

}

PVSWeb/src/com/sh/pvs/view/contabilidad/CompraVentaAccesoriosMBean.java
/**
	 * 	CompraVentaAccesoriosMBean.java:
	 * 
	 * 	Esta clase corresponde al Managed Bean para controlar el CRUD de 
	 * 	la entidad CompraVentaAccesorios
	 *
	 * @author Sergio Henao - sergiohenaoa@gmail.com - 11/04/2015
	 * @Modifier Sergio Henao - sergiohenaoa@gmail.com - 11/04/2015
	 * @version 1.0
	 * 
	 */
package com.sh.pvs.view.contabilidad;

import com.sh.pvs.core.interfaces.configuracion.IAccesorioServices;
import com.sh.pvs.core.interfaces.configuracion.ICuentaServices;
import com.sh.pvs.core.interfaces.contabilidad.IAccesorioxCompraVentaServices;
import com.sh.pvs.core.interfaces.contabilidad.ICompraVentaAccesoriosServices;
import com.sh.pvs.core.interfaces.seguridad.IUsuarioServices;
import com.sh.pvs.core.services.configuracion.AccesorioServices;
import com.sh.pvs.core.services.configuracion.CuentaServices;
import com.sh.pvs.core.services.contabilidad.AccesorioxCompraVentaServices;
import com.sh.pvs.core.services.contabilidad.CompraVentaAccesoriosServices;
import com.sh.pvs.core.services.contabilidad.MovimientoContableServices;
import com.sh.pvs.core.services.seguridad.UsuarioServices;
import com.sh.pvs.model.dto.configuracion.Accesorio;
import com.sh.pvs.model.dto.configuracion.Cuenta;
import com.sh.pvs.model.dto.contabilidad.AccesorioxCompraVenta;
import com.sh.pvs.model.dto.contabilidad.CompraVentaAccesorios;
import com.sh.pvs.model.dto.contabilidad.MovimientoContable;
import com.sh.pvs.model.dto.seguridad.Usuario;
import com.sh.pvs.view.utils.Constantes;
import com.sh.pvs.view.utils.ControlException;
import com.sh.pvs.view.utils.Metodos;
import org.primefaces.context.RequestContext;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletResponse;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.*;


@ManagedBean
@ViewScoped
public class CompraVentaAccesoriosMBean implements Serializable {

	/*Serializable Attribute*/
	private static final long serialVersionUID = 1L;
	
	/*Variables*/
	private CompraVentaAccesorios entity; 								// ViewForm - EditForm 	
 	private List<CompraVentaAccesorios> entityList; 					// Lista de registros del datatable
 	private List<CompraVentaAccesorios> entityFilterList;				// Lista de registros filtrados del datatable
 	private AccesorioxCompraVenta accesorioxCompraVenta;
 	private List<Accesorio> accesoriosDropDownList;
 	private List<Cuenta> cuentasDropDownList;
 	private List<Usuario> usuariosDropDownList;
 	private Usuario loggedUser;											//Usuario logeado (En Sesión)
 	
 	/*Navegación*/
 	private String mode;									// view - edit - list - create ==> Modo para identificar la vista
 	
 	/*Servicios*/
 	private ICompraVentaAccesoriosServices entityService;			// Servicios para la gestión de la entidad
	
 	/*Variables para navegación*/
 	public static String openDialog = "/contabilidad/compraVentaAccesoriosForm.faces";
 	public static String openWebMobile = "compraVentaAccesoriosForm.faces";
 	public static String closeRedirectMobile = "compraVentaAccesoriosList.faces";
	public static String closeRedirectWeb = "/contabilidad/compraVentaAccesoriosList.faces?faces-redirect=true";
	
	public static String openDialogAccesorio = "/contabilidad/accesorioxCompraVentaForm.faces";
 	public static String openWebMobileAccesorio = "accesorioxCompraVentaForm.faces";
 	
 	/*Constructors*/	
	/**	Default constructor */
	public CompraVentaAccesoriosMBean() {

	}
	
	/*METHODS*/
	
	/**
	 * Método para inicializar las variables
	 * 
	 * */
	@PostConstruct
	private void init(){
		
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			
			Metodos.loadSessionMesagges();
			
			loggedUser = Metodos.getUserSession();
			
			if(context.getExternalContext().getRequestParameterMap().get("mode") != null)
				mode = context.getExternalContext().getRequestParameterMap().get("mode");
			else
				mode = Constantes.MODELIST;
			
			if(mode.equals(Constantes.MODECREATE)){
				this.entity = new CompraVentaAccesorios();
				this.entity.setCuenta(new Cuenta());
				this.entity.setUsuario(new Usuario());
				fillCuentasDropDown();
				fillUsuariosDropDown();
				return;
			}
			
			if(mode.equals(Constantes.MODELIST)){
				fillEntityList();
				return;
			}
						
			if(mode.equals(Constantes.MODEVIEW) || mode.equals(Constantes.MODEEDIT)){
				
				try {
					
					String idParam = context.getExternalContext().getRequestParameterMap().get("id");
					entityService = new CompraVentaAccesoriosServices();
					entity = entityService.findById(Integer.parseInt(idParam));
					if(entity.getCuenta() == null){
						entity.setCuenta(new Cuenta());
					}
					if(mode.equals(Constantes.MODEEDIT)){
						fillCuentasDropDown();
						fillUsuariosDropDown();
					}
							
				} catch (Exception e) {
					context.addMessage(null,new FacesMessage(FacesMessage.SEVERITY_FATAL,ControlException.controlException(e), ""));
				}
				
				return;
			}
			
			//Si es la consulta de un accesorio
			if(mode.equals("ACCESORIOVIEW")){
				
				IAccesorioxCompraVentaServices accesorioSrv = new AccesorioxCompraVentaServices();
				String idaccesorio = context.getExternalContext().getRequestParameterMap().get("idaccesorio");
				accesorioxCompraVenta = accesorioSrv.findById(Integer.parseInt(idaccesorio));
				
				entityService = new CompraVentaAccesoriosServices();
				entity = entityService.findById(accesorioxCompraVenta.getCompraVentaAccesorios().getId());
				if(entity.getCuenta() == null){
					entity.setCuenta(new Cuenta());
				}
			}
			
			//Si es la creación de un accesorio
			if(mode.equals("ACCESORIONEW")){
				
				entityService = new CompraVentaAccesoriosServices();
				String idCVA = context.getExternalContext().getRequestParameterMap().get("idCVA");
				if(idCVA != null && !idCVA.equals("null")){
					entity = entityService.findById(Integer.parseInt(idCVA));
					if(entity.getCuenta() == null){
						entity.setCuenta(new Cuenta());
					}
				}else{
					entity = new CompraVentaAccesorios();
				}
				
				accesorioxCompraVenta = new AccesorioxCompraVenta();
				accesorioxCompraVenta.setCompraVentaAccesorios(entity);
				accesorioxCompraVenta.setAccesorio(new Accesorio());
				
				fillAccesoriosDropDown();
				
			}
			
		} catch (Exception e) {
			context.addMessage(null,new FacesMessage(FacesMessage.SEVERITY_FATAL,ControlException.controlException(e), ""));
		}
		
	}
	
	/**
	 * Create a new Accesorio entity
	 * 
	 */
	public String newEntity() throws Exception{
		
		entity = new CompraVentaAccesorios();
		
		FacesContext context = FacesContext.getCurrentInstance(); 
		HttpServletResponse response = (HttpServletResponse) context.getExternalContext().getResponse();
		response.sendRedirect(openWebMobile + "?mode=" + Constantes.MODECREATE);
		
		return "";
		
	}
	
	/**
	 * Select an existing CompraVentaAccesorios entity
	 * 
	 */
	public String selectEntity(Integer idKey) throws Exception {			
		
		FacesContext context = FacesContext.getCurrentInstance(); 
		HttpServletResponse response = (HttpServletResponse) context.getExternalContext().getResponse();
		response.sendRedirect(openWebMobile + "?id=" + idKey + "&mode=" + Constantes.MODEVIEW);
		
		return "";
	}
	
	/**
	 * Edit an existing CompraVentaAccesorios entity
	 * 
	 */
	public String editEntity(Integer idKey, boolean fromList) throws Exception {
		
		FacesContext context = FacesContext.getCurrentInstance(); 
		HttpServletResponse response = (HttpServletResponse) context.getExternalContext().getResponse();
		response.sendRedirect(openWebMobile + "?id=" + idKey + "&mode=" + Constantes.MODEEDIT);
		
		return "";
		
	}
	
	/**
	 * Delete an existing CompraVentaAccesorios entity
	 * 
	 */
	public String deleteEntity(Integer idKey, boolean fromList) {
		
		FacesContext context = FacesContext.getCurrentInstance(); 
		
		try {
			entityService = new CompraVentaAccesoriosServices();
			entity = entityService.findById(idKey);
			if(entity.getCuenta() == null){
				entity.setCuenta(new Cuenta());
			}
			entityService.deleteTX(entity);
			
			Metodos.auditLog(Constantes.ACTIONDELETE, CompraVentaAccesoriosMBean.class.getSimpleName(), entity.getNroFactura(), "");
			
			String msg = Metodos.getMessageResourceString("generics_eliminarOK", new Object[]{entity.getNroFactura()});
			if(!fromList || (!Metodos.isMobile() && Metodos.isDlg())){
				Metodos.setSessionMesagges(Constantes.SESSIONMSGINFO, msg);
			}
				
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, msg, "")); // MENSAJE
				
			fillEntityList();
		} catch (Exception e) {
			context.addMessage(null,new FacesMessage(FacesMessage.SEVERITY_FATAL,ControlException.controlException(e), ""));
		}
		return  Metodos.close(closeRedirectWeb, closeRedirectMobile, fromList);
		
	}
	
	/**
	 * Metodo que retorna las listas
	 * @return
	 */
	public void fillEntityList(){
		FacesContext context = FacesContext.getCurrentInstance(); 
		try {
			entityService = new CompraVentaAccesoriosServices();
			entityList = entityService.findAll(loggedUser.getCompania().getId());
			
		} catch (Exception e) {
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, ControlException.controlException(e), ""));
		}		
	}
	
	/**
	 * Metodo para guardar
	 */
	public String saveEntity(){
		
		FacesContext context = FacesContext.getCurrentInstance(); 
		
		try{
			if(entity.getEsPagado()){
				entity.setPlazo(0);
			}
			if(mode != null && mode.equals(Constantes.MODECREATE)
					&& hasPermissionTo(Constantes.ACTIONCREATE)){
				
				entity.setCompania(loggedUser.getCompania());
				entityService = new CompraVentaAccesoriosServices();
				if(entity.getCuenta() != null && 
						(entity.getCuenta().getId() == null || entity.getCuenta().getId().equals(new Integer(0)))){
					entity.setCuenta(null);
				}
				entityService.createTX(entity);
				

PVSWeb/src/com/sh/pvs/view/contabilidad/ReporteCarteraMBean.java
/**
	 * 	MovimientoCarteraMBean.java:
	 * 
	 * 	Esta clase corresponde al Managed Bean para controlar el CRUD de 
	 * 	la entidad MovimientoCartera
	 *
	 * @author Sergio Henao - sergiohenaoa@gmail.com - 11/04/2015
	 * @Modifier Sergio Henao - sergiohenaoa@gmail.com - 11/04/2015
	 * @version 1.0
	 * 
	 */
package com.sh.pvs.view.contabilidad;

import java.io.Serializable;
import java.util.Iterator;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import com.sh.pvs.core.interfaces.contabilidad.IReporteCarteraServices;
import com.sh.pvs.core.services.contabilidad.ReporteCarteraServices;
import com.sh.pvs.model.dto.contabilidad.ReporteCarteraRow;
import com.sh.pvs.model.dto.seguridad.Usuario;
import com.sh.pvs.view.utils.Constantes;
import com.sh.pvs.view.utils.ControlException;
import com.sh.pvs.view.utils.Metodos;

@ManagedBean
@ViewScoped
public class ReporteCarteraMBean implements Serializable {

	/*Serializable Attribute*/
	private static final long serialVersionUID = 1L;
	
	/*Variables*/
	private Boolean compraPPago = false;
	private Boolean ventaPCobro = false;
	private Boolean pagosPVendedor = false;
	private Boolean cobrosPVendedor = false;
	private Boolean pagosPComprador = false;
	private Boolean cobrosPComprador = false;
 	private List<ReporteCarteraRow> entityList; 				// Lista de registros del datatable
 	private Usuario loggedUser;									//Usuario logeado (En Sesión)
 	
 	/*Navegación*/
 	private String mode;									// view - edit - list - create ==> Modo para identificar la vista
 	
 	/*Servicios*/
 	private IReporteCarteraServices entityService;			// Servicios para la gestión de la entidad
	
 	/*Variables para navegación*/
 	public static String openDialog = "/contabilidad/reporteCarteraForm.faces";
 	public static String openWebMobile = "reporteCarteraForm.faces";
 	public static String closeRedirectMobile = "reporteCarteraFormList.faces";
	public static String closeRedirectWeb = "/contabilidad/reporteCarteraFormList.faces?faces-redirect=true";
 	
 	/*Constructors*/	
	/**	Default constructor */
	public ReporteCarteraMBean() {

	}
	
	/*METHODS*/
	
	/**
	 * Método para inicializar las variables
	 * 
	 * */
	@PostConstruct
	private void init(){
		
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			
			Metodos.loadSessionMesagges();
			
			loggedUser = Metodos.getUserSession();
			
			if(context.getExternalContext().getRequestParameterMap().get("mode") != null)
				mode = context.getExternalContext().getRequestParameterMap().get("mode");
			else
				mode = Constantes.MODELIST;
			
			if(mode.equals(Constantes.MODELIST)){
				fillEntityList();
				return;
			}
						
		} catch (Exception e) {
			context.addMessage(null,new FacesMessage(FacesMessage.SEVERITY_FATAL,ControlException.controlException(e), ""));
		}
		
	}
	
	/**
	 * Metodo que retorna las listas
	 * @return
	 */
	public void fillEntityList(){
		FacesContext context = FacesContext.getCurrentInstance(); 
		try {
			entityService = new ReporteCarteraServices(null);
			entityList = null;
			entityList = entityService.findAllMovtos(compraPPago, ventaPCobro, 
					pagosPVendedor, cobrosPVendedor, pagosPComprador, cobrosPComprador, loggedUser.getCompania().getId());
			
		} catch (Exception e) {
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, ControlException.controlException(e), ""));
		}		
	}
	
	/* SECURITY METHODS*/
	/**
	 * Método que valida si el usuario en sesión puede ejecutar una acción sobre este documento
	 * 
	 * @return
	 */
	public boolean hasPermissionTo(String action){		
		return Metodos.hasPermission(ReporteCarteraMBean.class.getSimpleName(), action);
	}

	/* GETTERS AND SETTERS */
	public Double getValorTotal() {
		Double ingresos = 0.0;
		if(entityList != null && entityList.size()>0){
			for (Iterator<ReporteCarteraRow> itRows = entityList.iterator(); itRows.hasNext();) {
				ReporteCarteraRow row = (ReporteCarteraRow) itRows.next();
				if(row.getValor() != null)
					ingresos += row.getValor();
			}
		}
		return ingresos;
	}

	public List<ReporteCarteraRow> getEntityList() {
		return entityList;
	}

	public void setEntityList(List<ReporteCarteraRow> entityList) {
		this.entityList = entityList;
	}

	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	public Boolean getCompraPPago() {
		return compraPPago;
	}
	
	public void setCompraPPago(Boolean compraPPago) {
		this.compraPPago = compraPPago;
	}
	
	public Boolean getVentaPCobro() {
		return ventaPCobro;
	}

	public void setVentaPCobro(Boolean ventaPCobro) {
		this.ventaPCobro = ventaPCobro;
	}
	
	public Boolean getPagosPVendedor() {
		return pagosPVendedor;
	}

	public void setPagosPVendedor(Boolean pagosPVendedor) {
		this.pagosPVendedor = pagosPVendedor;
	}

	public Boolean getCobrosPComprador() {
		return cobrosPComprador;
	}

	public void setCobrosPComprador(Boolean cobrosPComprador) {
		this.cobrosPComprador = cobrosPComprador;
	}

	
	public Boolean getCobrosPVendedor() {
		return cobrosPVendedor;
	}
	

	public void setCobrosPVendedor(Boolean cobrosPVendedor) {
		this.cobrosPVendedor = cobrosPVendedor;
	}
	

	public Boolean getPagosPComprador() {
		return pagosPComprador;
	}
	

	public void setPagosPComprador(Boolean pagosPComprador) {
		this.pagosPComprador = pagosPComprador;
	}
	
}

PVSWeb/WebRoot/contabilidad/reporteCarteraList.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/generics/template.xhtml">
	
	<ui:define name="content">
			
		<h:form id="frm">
		
			<div class="ui-grid ui-grid-responsive">
				<div class="ui-grid-row">
					<div class="ui-grid-col-12 list_title">
						<p:outputLabel value="#{msg.reporteCartera_Title}"/>
					</div>
				</div>
				<div class="ui-grid-row">
					<div class="ui-grid-col-12">
						<div>#{msg.reporteCartera_Filtros}</div>
						<p:separator/>
						<p:panelGrid styleClass="crud-panelgrid-reporte">
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_CompraPPago}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.compraPPago}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_VentaPCobro}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.ventaPCobro}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_PagoPComprador}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.pagosPComprador}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_CobroPComprador}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.cobrosPComprador}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_PagoPVendedor}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.pagosPVendedor}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column>
									<p:outputLabel 
										value="#{msg.reporteCartera_Filtros_CobroPVendedor}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column>
									<p:selectBooleanCheckbox value="#{reporteCarteraMBean.cobrosPVendedor}"></p:selectBooleanCheckbox>
								</p:column>
							</p:row>
							<p:row>
								<p:column colspan="4">
									<p:commandButton
										value="#{msg.reporteCartera_BtnBuscar}"
										actionListener="#{reporteCarteraMBean.fillEntityList()}"
										styleClass="list-button-add-new"
										process="frm"
										ajax="false"
										onclick="PF('statusDialog').show()" oncomplete="PF('statusDialog').hide()">
									</p:commandButton>
								</p:column>
							</p:row>
							<p:row>
								<p:column style="text-align:right">
									
								</p:column>
								<p:column style="text-align:right">
									
								</p:column>
								<p:column style="text-align:right">
									<p:outputLabel 
										value="#{msg.reporteCartera_Totales_ValorTotal}:"
										styleClass="crud-field-label" />
								</p:column>
								<p:column style="text-align:right">
									<p:outputLabel 
										value="#{reporteCarteraMBean.valorTotal}"
										styleClass="crud-field-value">
										<f:convertNumber type="currency" currencySymbol="$" maxFractionDigits="0"/>
									</p:outputLabel>
								</p:column>
							</p:row>
						</p:panelGrid>
					</div>
				</div>
				
				<div class="ui-grid-row">
					<div class="ui-grid-col-12" style="text-align: right; margin-right: 20px">
						<h:commandLink>
			                <p:graphicImage name="/images/DEFAULT/excel.png" width="24"/>
			                <p:dataExporter type="xls" target="dta" fileName="reporteCartera" />
			            </h:commandLink>
			 
					</div>
				</div>
				           
				
				<div class="ui-grid-row">
					<div class="ui-grid-col-12">
					
						<!-- Sección del datatable -->
						<p:dataTable
							id="dta" 
							widgetVar="dtaWV"
							var="entity" 
							value="#{reporteCarteraMBean.entityList}"
							emptyMessage="#{msg.generics_RegistrosNoEncontrados}"
							paginator="true"
							rows="100"
							paginatorTemplate="  {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
							currentPageReportTemplate="({currentPage} de {totalPages})"
							sortMode="multiple"
							styleClass="list-datatable">
							
							<f:facet name="footer">
							 	<h:outputFormat value="#{msg.generics_list_total}" 
							 		rendered="#{reporteCarteraMBean.entityList != null}">
							 		 <f:param value="#{reporteCarteraMBean.entityList.size()}" />
							 	</h:outputFormat>
							</f:facet>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_Origen}"
								sortBy="#{entity.origen}"
								width="180">
								<h:outputText value="#{entity.origen}" />
							</p:column>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_Fecha}"
								sortBy="#{entity.fecha}"
								width="80">
								<h:outputText value="#{entity.fecha}">
									<f:convertDateTime pattern="dd/MM/yyyy" />
								</h:outputText>
							</p:column>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_Descripcion}"
								sortBy="#{entity.descripcion}">
								<h:outputText value="#{entity.descripcion}" />
							</p:column>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_FechaV}"
								sortBy="#{entity.fechaV}"
								width="80">
								<h:outputText value="#{entity.fechaV}">
									<f:convertDateTime pattern="dd/MM/yyyy" />
								</h:outputText>
							</p:column>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_Plazo}"
								sortBy="#{entity.plazo}"
								width="100">
								<h:outputText value="#{entity.plazo}">
									<f:convertNumber type="number" maxFractionDigits="0"/>
								</h:outputText>
							</p:column>
							
							<p:column
								headerText="#{msg.reporteCartera_Tabla_Valor}"
								sortBy="#{entity.valor}"
								width="100">
								<h:outputText value="#{entity.valor}">
									<f:convertNumber type="currency" currencySymbol="$" maxFractionDigits="0"/>
								</h:outputText>
							</p:column>
							
		                </p:dataTable>
					</div>
				</div>
				
			</div>
			
			<ui:include src="/generics/generics.xhtml"/>
			
		</h:form>
	</ui:define>
</ui:composition>
	